### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by ai** [AleshaOleg/postcss-sass#1]
Add more docs. You can take a example from `postcss-scss`. Main things that we need to mention:

1. How to use it. Step by step.
2. Warning, that it does not compile Sass to CSS. it is only tool for Stylelint and other tools working with sources

**Comment by AleshaOleg** [comment]
Updated.

**Comment by ai** [comment]
1. Add code highlight.
2. Add warning that this parser doesn’t compile Sass.
3. Add better examples.

See `postcs-scss` docs for example.

**Comment by AleshaOleg** [comment]
Added
