### ISSUE TITLE
How do I use it in gulp?

### ISSUE THREAD

**Issue by guohuihot** [AleshaOleg/postcss-sass#10]
How do I use it in gulp?

**Comment by AleshaOleg** [comment]
It will be the same with [postcss-scss](https://github.com/postcss/postcss-scss). [Here](https://github.com/postcss/postcss-scss/issues/10) is an example. But instead of `syntax:` use `parser:`. Thanks, for your question!

**Comment by AleshaOleg** [comment]
@guohuihot the simple example:

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');

gulp.task('default', function () {
    return gulp.src('../../__tests__/sass/basic.sass')
        .pipe(postcss([], {
            parser: require('../../.'),
            stringifier: require('../../stringify')
        }))
        .pipe(gulp.dest('./result'));
});

```

**Comment by AleshaOleg** [comment]
@easherma https://github.com/postcss/gulp-postcss#passing-additional-options-to-postcss

**Comment by easherma** [comment]
@AleshaOleg I understand that, I'd suggest adding it to your docs too or at least include the same explanation + link

**Comment by gucong3000** [comment]
https://www.npmjs.com/package/gulp-html-postcss
I think it is better.
