### ISSUE TITLE
Check by gonzales-pe author

### ISSUE THREAD

**Issue by AleshaOleg** [AleshaOleg/postcss-sass#2]
Hey @tonyganch. As you can see, I wrote a converter (actually it have basic support, so it not tested for mixins/variables and other complex things) from Sass to PostCSS AST, using [gonzales-pe](https://github.com/tonyganch/gonzales-pe). Could you check, before I didn't started to develop more complexity things, may be I missed some specific details? Thanks!

**Comment by tonyganch** [comment]
Are you planning for `postcss-sass` to always use gpe underneath or is it a temporary solution?
I'm asking to see if you will make me work on parser's speed issues after that and fix bugs within a day :)

**Comment by AleshaOleg** [comment]
Actually - no. Firstly, it was idea to implement this one from [dart-sass](https://github.com/sass/dart-sass). But, unfortunately, they didn't implemented method to get SASS AST, yet. We [told](https://github.com/sass/dart-sass/issues/88) about this problem in issues, but it takes a lot of problems to implement `postcss-sass` with `dart-css`. So, yes it's not temporary solution for converter. Maybe, some day it will be implemented on Dart language, but I have no idea when we can get AST for `dart-sass`.

**Comment by tonyganch** [comment]
First of all, @ai, ![image](https://cloud.githubusercontent.com/assets/872004/23330235/7bf4702e-fb49-11e6-907b-718403af6295.png)

**Comment by tonyganch** [comment]
@AleshaOleg, I looked at your code quickly and I don't see what to comment on. You traverse through nodes and if the result works for you, than you do everything right :)
Please let me know if you need any changes made in gpe to make your work a bit easier, and I'll keep in mind to update you on any upcoming major changes in api or ast.

**Comment by AleshaOleg** [comment]
@tonyganch thanks for your check, first of all i need a source for current node in Sass AST. Is it possible to implement this feature in gpe? If yes, how quickly? I also can help to do this. Firstly need to create issue in gpe repo, right?

**Comment by tonyganch** [comment]
I'm not sure I understand what exactly you need, an example will help a lot, feel free to create an issue

**Comment by AleshaOleg** [comment]
Sorry:) I thought it will be easy to understand, I need to have a pure CSS from current node. For example for this Sass:

```
div a
  color: black
```

I need to have what I have a source in AST, like this:

`div a/n  color: red`

I think it will be a much easier to get it from input Sass, which I give to gpe, and not collect
sources from AST. What you think?

**Comment by tonyganch** [comment]
You can either use `node.toString()` (see https://github.com/tonyganch/gonzales-pe#parsetreetostring), or use start/end position of the node to somehow cut your source string.
I would like to avoid storing Sass string as it is for every node (say, in a property `node.source`), because that will needlessly duplicate information (a lot) while not bringing much benefit over `node.toString()`.

**Comment by AleshaOleg** [comment]
@tonyganch oh, thanks a lot! Didn't know about this method:(

**Comment by ai** [comment]
I think we can close this issue
