### ISSUE TITLE
Mathjs vulnerability

### ISSUE THREAD

**Issue by jondavidjohn** [AleshaOleg/postcss-sass#24]
https://nodesecurity.io/advisories/552

This would require an upgrade to at least `mathjs@3.17.0`

**Comment by AleshaOleg** [comment]
Thanks for issue. Current version (0.2.0) of postcss-sass actually don't use a `mathjs` - https://github.com/AleshaOleg/postcss-sass/blob/master/package.json#L19. Please update `postcss-sass` to latest version.
