### ISSUE TITLE
variables identified as declaration

### ISSUE THREAD

**Issue by thomashandorf** [AleshaOleg/postcss-sass#54]
Hi, 

when translating a simple file with a variable, this variable is identified as "decl":

```
{
  "raws": {
    "before": "",
    "between": ":    ",
    "semicolon": false
  },
  "type": "decl",
  "prop": "$font-stack",
  "value": "Helvetica, sans-serif",
  "source": {
    "start": {
      "line": 1,
      "column": 1
    },
    "end": {
      "line": 1,
      "column": 37
    },
    "input": {
      "css": "$font-stack:    Helvetica, sans-serif\n$primary-color: #333\n\np\n  ... ",
      "id": "<input css 1>"
    }
  }
}
```

is this intentionally or a bug? in the former case is there a way to find out that it is a variable?

**Comment by AleshaOleg** [comment]
@thomashandorf Basically, in postcss AST [declaration](http://api.postcss.org/Declaration.html) is everything that has a property and value, like `color: red`. So, postcss don't have something like `type: variable` Do you need to detect somehow if it's a variable? I think you can ask anybody from @stylelint team how they're dealing with this. Or maybe @gucong3000 you can help with this?

**Comment by AleshaOleg** [comment]
@thomashandorf I think they're doing detecting of variables here - https://github.com/stylelint/stylelint/blob/f6fbad37e1ffa84aed4a996b3829b4275e7320c5/lib/utils/isStandardSyntaxValue.js#L17 😄

**Comment by thomashandorf** [comment]
@AleshaOleg thanks for looking into this. So i guess we'll need to detect variables at a later step by /^$/.  Thanks!

**Comment by AleshaOleg** [comment]
@thomashandorf yes.
