### ISSUE TITLE
"syntax: require('postcss-sass')" returns and undefined parse error

### ISSUE THREAD

**Issue by Gespinha** [AleshaOleg/postcss-sass#8]
Hey,

I've tried building postcss-sass into my tasks, but it constantly returns and error: "Cannot read property 'parse' of undefined".

After running the task on verbose mode I can see that the syntax is definitely undefined after calling the dependency like so:

```
        postcss: {
            options: {
              processors: [
                require('postcss-sorting')({
                    'clean-empty-lines': true
                })
              ],
              syntax: require('postcss-sass')
            },
            dist: {
              src: '*.sass'
            }
        },
```

Any clues on what is going on? Am I doing anything wrong here?

Thanks!

**Comment by AleshaOleg** [comment]
Hey, could you show you code example of Sass?

**Comment by Gespinha** [comment]
I'm currently testing it on a very simple SASS file:

```
body
    background: #000

.one
    background: #000

    .two
        background: #f00

    .three
        background: #f00
```

No issues here I think and I've made sure that "postcss-sass" is installed on npm and that grunt is importing all the requires dependencies.

**Comment by Gespinha** [comment]
I've checked and everything is fine, I've even tested the same grunt task with "postcss-scss" and it works fine. But only when I try with "postcss-sass" does it return "syntax: undefined"

**Comment by AleshaOleg** [comment]
@Gespinha ok, send me Grunt config and package.json - I need to check it. Thanks

**Comment by Gespinha** [comment]
My grunt config is this:

```
module.exports = function (grunt) {
    'use strict';
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        postcss: {
            options: {
              processors: [
                require('postcss-sorting')({
                    'clean-empty-lines': true
                })
              ],
              syntax: require('postcss-sass')
            },
            dist: {
              src: '*.sass'
            }
        }
    });

    grunt.loadNpmTasks('grunt-postcss');

    grunt.registerTask('default', ['postcss']);
};
```

And my package.json is this:

```
{
  "name": "test",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.2",
    "grunt-postcss": "^0.8.0",
    "postcss-sass": "^0.1.0",
    "postcss-sorting": "^2.0.1"
  }
}

```

**Comment by ai** [comment]
@Gespinha `syntax:` → `parser:` will solve a problem.

`postcss-sass` can only be a parser right now and have no way to stringify sources.

**Comment by ai** [comment]
I will fix `postcss` DX for this case — we definatelly need better warning for this typo https://github.com/postcss/postcss/issues/1024

**Comment by Gespinha** [comment]
@ai yup you're right, that did fix the issue. I was almost sure I tried that before, but probably did something wrong.

I agree, these typos probably need some more details on the warning messages.

Thanks for the help!
