### ISSUE TITLE
Running postcss with postcss-sass changes the syntax of the file

### ISSUE THREAD

**Issue by gespinha** [AleshaOleg/postcss-sass#9]
Hey!

After running my grunt task which contains the following postcss-sorting and postcss-sass config:

```
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        postcss: {
            options: {
              processors: [
                require('postcss-sorting')({
                    'clean-empty-lines': true,
                    'rule-nested-empty-line-before': [true, { except: ["first-nested"] }]
                })
              ],
              parser: require('postcss-sass')
            },
            dist: {
              src: '*.sass'
            }
        }
    });
```

My file which was this:

```
body
    background: #000

.one
    background: #000

    .two
        background: #f00

    .three
        background: #f00
```

transformed into this:

```
body
{background: #000
}
.one
{background: #000
}
.one .two
{background: #f00
}
.one .three
{background: #f00
}
```

I have a couple of options set in postcss-sorting, but the only result I get is this, regardless of the options set.

**Comment by AleshaOleg** [comment]
@Gespinha hey again:) Sass syntax not supports brackets - `{}`

**Comment by Gespinha** [comment]
@AleshaOleg Hey! Yes, I know. The "{}" are being added after I run the postcss with postcss-sass as dependency.

**Comment by AleshaOleg** [comment]
@Gespinha sorry, misunderstood you. Deleted, previous comment

**Comment by AleshaOleg** [comment]
@Gespinha I think it's a [postcss-sorting](https://github.com/hudochenkov/postcss-sorting) issue. Could you create issue on that project? I will help, if any problems will be.

Do you really need this feature? Or just testing? I can help to implement Sass syntax in `postcss-sorting`.

**Comment by AleshaOleg** [comment]
Oh, I see it

https://github.com/hudochenkov/postcss-sorting/issues/57

**Comment by Gespinha** [comment]
Yes, I looked for help there, because it wasn't working initially. But now that I got it working, even if I disable postcss-sorting, its converting my syntax and adding the "{}" to the layout, so I don't think its an issue on postcss-sorting

**Comment by ai** [comment]
It happens because `postcss-sass` is only parser.

Sass → `postcss-sass` → CSS AST → default (CSS) stringifier → CSS

If you want to convert Sass → Sass, you need to add Sass stringifier to `postcss-sass`

**Comment by AleshaOleg** [comment]
@gespinha I update `postcss-sass` to `0.2.0`, now all works properly.
